name: Build and push any image to DockerHub

inputs:
  username:
    required: true
  password:
    required: true
  context:
    required: true
  push:
    required: false
    default: true
  tags:
    required: true

runs:
  using: "composite"

  steps:
    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: ${{ inputs.context }}
        push: ${{ inputs.push }}
        tags: ${{ inputs.tags }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
